(source gnu)
(source marmalade)
(source melpa)

(depends-on "async")
(depends-on "auto-complete")
(depends-on "cask")
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "findr")
(depends-on "ghub")
(depends-on "git-commit")
(depends-on "inf-ruby")
(depends-on "inflections")
(depends-on "init-loader")
(depends-on "jump")
(depends-on "let-alist")
(depends-on "magit")
(depends-on "magit-popup")
(depends-on "package-build")
(depends-on "pallet")
(depends-on "pkg-info")
(depends-on "popup")
(depends-on "queue")
(depends-on "rinari")
(depends-on "robe")
(depends-on "rspec-mode")
(depends-on "ruby-block")
(depends-on "ruby-compilation")
(depends-on "ruby-end")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-interpolation")
(depends-on "ruby-tools")
(depends-on "s")
(depends-on "seq")
(depends-on "shut-up")
(depends-on "spinner")
(depends-on "with-editor")

(depends-on "restclient")

;; Theme
(depends-on "solarized-theme")
(depends-on "darcula-theme")

;; Find-In-Project and Ctrl-P
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-ag")

;; bash shell
(depends-on "bash-completion")
